FALCON-2031 Hcat Retention test cases are failing NoClassDefFoundError
Please review the following pull request, in which we have added the "oozie.action.sharelib.for.java" = "hcatalog,hive" in eviction-action.xml to avoid the failure of HCat retention test cases with "NoClassDefFoundError" when using latest Hive.

Author: peeyush b <pbishnoi@hortonworks.com>

Reviewers: Pallavi Rao <pallavi.rao@inmobi.com>, Praveen Adlakha <adlakha.praveen@gmail.com>, sandeep <sandysmdl@gmail.com>, Balu <balu@apache.org>

Closes #185 from peeyushb/FALCON-2031

(cherry picked from commit e7cdda742f90744519f522fcf499f79debfeb945)
Signed-off-by: peeyush b <pbishnoi@hortonworks.com>